### ISSUE TITLE
what's the ship list for using coffee-table at work?

### ISSUE THREAD

**Issue by ryandm** [jimtla/coffee-table#12]
Ive had fun playing around with this, but I'm getting that niggling feeling that says we should ship something :)

Jim, I'm guessing you don't use ct at work quite yet...what's the smallest possible ship list we could complete that would enable you to start using this at work?

I'll think about this question with regard to some little side project of mine, and @AlexeyMK @ldvchen might have ideas from their experiences as well, but since afaik you're the only one who does full time work in coffeescript your thoughts here are likely the most valuable.

**Comment by jimtla** [comment]
I currently use sublime text for editing. The major things missing from ct (in rough order of importance) are:
- More vim features, I think the most pressing to me are yank/paste and undo, although I'm sure we'll discover others in the process of trying to implement those.
- Good file switching (Looks like [this](http://cl.ly/image/0V422i3r1I15) in sublime)
- Syntax hilighting
- Search (Less important because cmd-f does an okay job)

I think I would start using it without syntax hilighting or search, so that leaves a pretty short list.

**Comment by ryandm** [comment]
I want file switching as well, I can work on that. In the screenshot, what do the big blue numbers mean?

@AlexeyMK looks like y/p are much more important than I'd expected...are you still interested in working on them?

@jimtla , @ldvchen , anything you care to work on in particular? feel free to steal file switching from me if needed

**Comment by jimtla** [comment]
Big blue numbers are some kind of relevancy score - not particularly useful. 
I'm going to take a stab at undo/redo next.

**Comment by ryandm** [comment]
thanks. As we think about this from the make-it-usable angle, I'm starting to wonder about the why's-it-better angle as well. I'd enjoy making an explicit list of ways in which we expect this to be better to alternatives. So far my list of related alternatives is just traditional workflow, and https://c9.io/

**Comment by AlexeyMK** [comment]
Out of commission this weekend, sadly. Hopefully have time next week but
don't want to commit and not execute
