### ISSUE TITLE
editor should gracefully handle non-qwerty keyboard layouts

### ISSUE THREAD

**Issue by ryandm** [jimtla/coffee-table#4]
We/I should do some research to figure out how people usually handle this.

**Comment by jimtla** [comment]
Agreed - my two initial thoughts on that are:
(good version) figure out a way to detect the character that was depressed instead of the keyboard scancode.
(less good version) map each keyboard layout, and then have them bang on their keyboard while focused on a textarea to auto-detect the layout, alternately have them type every key and record the mapping that way so we don't need to manually map each type of keyboard.

The benefit of the second one is that I know how to do it.

**Comment by ryandm** [comment]
What about the editable-content thing that all the rich text editors use? Do you have any experience/knowledge that suggests how good an approach that would be?

**Comment by jimtla** [comment]
content-editable - I have very slight experience that leads me to believe it is a world of pain and sadness (especially across browsers) but it's worth looking into.

**Comment by ryandm** [comment]
Handled in #10
